version: "3"
services:
  connect-app:
    image: "sinatra-connect-app"
    build: .
    environment:
      - "APP_ENV=production"
      - "WATCHMEN_DATABASE_HOST=influxdb"
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - grafana-storage:/var/lib/grafana
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    environment:
      - "GF_INSTALL_PLUGINS=grafana-worldmap-panel"
    ports:
      - "3000:3000"
volumes:
  grafana-storage:
